# Generated by Django 6.0.7 on 2026-07-19 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime(2026, 7, 19, 12, 52, 34, 996949, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
