# Generated by Django 6.0.7 on 2026-07-19 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0003_alter_product_created_at_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2026, 7, 19, 17, 10, 2, 71472, tzinfo=datetime.timezone.utc)),
        ),
    ]
