# Generated by Django 6.0.7 on 2026-07-20 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0005_remove_cart_created_at_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2026, 7, 20, 14, 22, 18, 457858, tzinfo=datetime.timezone.utc)),
        ),
    ]
