# Generated by Django 6.0.7 on 2026-07-20 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0006_alter_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2026, 7, 20, 14, 23, 31, 907509, tzinfo=datetime.timezone.utc)),
        ),
    ]
