# Generated by Django 6.0.7 on 2026-07-20 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0008_alter_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2026, 7, 20, 20, 24, 50, 774792, tzinfo=datetime.timezone.utc)),
        ),
    ]
